### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by rorynolan** [ropensci/bittrex#10]
In the documentation of `bt_sell()`, it says 
`quantity`   how much of the base currency to sell.
This should be the _quote_ currency and not the _base_ currency. 

I also feel that `bt_buy()` and `bt_sell()` could do with a few more examples, and that the documentation of `rate` should mention the word "price". Happy to submit these changes as a PR if you'd like. Let me know.

Regards,
Rory

**Comment by kaneplusplus** [comment]
Shoot, thanks for pointing this out. 

PR's are very welcome and I agree that `bt_buy()` and `bt_sell()` should be clearer.

**Comment by rorynolan** [comment]
Alrighty. I'll prepare a PR to sort this out.
