### ISSUE TITLE
API changed

### ISSUE THREAD

**Issue by madsurgeon** [ropensci/bittrex#12]
It seems that the Bittrex account API now requires a nonce: https://bittrex.com/Home/Api

Requesting e.g. https://bittrex.com/api/v1.1/account/getbalances?apikey=API_KEY results in the error message: "NONCE_NOT_PROVIDED".

The R package gives the error: 

```
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
9. parse_string(txt, bigint_as_char)
8. parseJSON(txt, bigint_as_char)
7. fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, ...)
6. jsonlite::fromJSON(parse_text(x, encoding = "UTF-8"), simplifyVector = simplifyVector, ...)
5. parser(x = content, type = type, encoding = encoding, ...)
4. parse_auto(raw, type, encoding, ...)
3. content(GET(req, add_headers(apisign = sig)), type = "application/json")
2. priv_req(req)
1. getbalances()
```

**Comment by kaneplusplus** [comment]
Also, you did provide keys for authentication with `bt_authenticate` first, correct?

**Comment by madsurgeon** [comment]
Ok, this is very strange. Now it works again. I did not change anything in my code. It simply threw the error above for two days and now it works again. Did Bittrex ban me for two days for some reason??
I don't think I overdid my requests though.
Anyway, I think you can close this issue since it seems to be due to Bittrex' side.
Thanks!

**Comment by kaneplusplus** [comment]
It's no problem. I have seen this before and I'm not sure what causes it. I'm also hesitant to add a "retry" option since the package is focused on only implementing the API. This might be a nice function for the [bittrextools package](https://github.com/kaneplusplus/bittrextools), which tries to add some higher-level functionality.
