### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by maelle** [ropensci/bittrex#14]
@kaneplusplus :wave:

I've seen several Appveyor webhooks issues over ropensci repos, including for builds under maintainers' account like yours, sorry about that.

Could you please have a look at https://github.com/ropensci/bittrex/settings/hooks/14018599 / email Appveyor team? Thanks!

By the way the README badge doesn't point to the builds. We've stopped transferring builds to ropensci accounts, sorry about that.

**Comment by kaneplusplus** [comment]
Sorry, I don't understand why you want me to email the Appveyor team. Is there an issue or question here?

**Comment by kaneplusplus** [comment]
OK, I'm almost caught up. Given that the package is R-only, it might be easiest to remove Appveyor.

**Comment by maelle** [comment]
If no conditions in https://github.com/ropensci/onboarding-meta/issues/48 apply, it can be easier yes!

**Comment by maelle** [comment]
Maybe try that first (email received this night from Appveyor)

* New commit and push (the "account" was blocked, unclear to me whether they mean Appveyor or GitHub...)

*  If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 *   If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account.

**Comment by kaneplusplus** [comment]
@maelle Thanks very much for your help. I'm not able to get AppVeyor working and since it's not a requirement for my package (as you point out), I've removed the badge. I'll leave the issue open though to remind me to see if anything changes in the next couple of weeks.

**Comment by maelle** [comment]
Cool thanks! Not a very user-friendly service in my opinion so thanks a ton for your patience.

**Comment by maelle** [comment]
Should you/Can I remove the broken webhook since it's not used? https://github.com/ropensci/bittrex/settings/hooks/14018599 Thanks!

**Comment by kaneplusplus** [comment]
@maelle Done. Thanks for pointing this out.

**Comment by maelle** [comment]
Thank _you_!
