### ISSUE TITLE
Decorate returned data.frame objects

### ISSUE THREAD

**Issue by kaneplusplus** [ropensci/bittrex#2]
It might be nice to allow users to change the `data.frame` objects returned by the functions so that they have other types (like `tibble` or `data.table`). This would involve registering a function with the package so each time a `data.frame` is generated it could be passed to a specified function.

**Comment by noamross** [comment]
This is an interesting idea, but I wonder if it would benefit from a more general treatment - either a standalone package or a set of programming conventions for package developers.  I imagine the user would want to set an option like this globally (via .Rprofile or .Renviron), and then all package developers who are on board could use a similar hook for their data frame outputs.  Alternatively, one might make a package that overrides `print.data.frame` or other print methods.

**Comment by kaneplusplus** [comment]
I like the idea of a package that wraps this one along with similar ones. Especially since I also have this [ccex](https://github.com/kaneplusplus/ccex) package. I'll think about what a higher-level inter-exchange package should look like.
