### ISSUE TITLE
documented installation does not function

### ISSUE THREAD

**Issue by j4rd44** [ropensci/bittrex#5]
> devtools::install_github("ropensci/bittrex")
Downloading GitHub repo ropensci/bittrex@master
from URL https://api.github.com/repos/ropensci/bittrex/zipball/master
Installation failed: error in running command

**Comment by kaneplusplus** [comment]
I'm having trouble reproducing this. It looks like you have `devtools` installed. 

Do you have an internet connection?

**Comment by j4rd44** [comment]
Thanks for investigating my issue.
I believe, that my internet connection is not the source of this issue.
Tried this as root and also as regular user, but with the same outcome ("error in running command").
My box runs opensuse tumbleweed and R version 3.4.1 (2017-06-30) -- "Single Candle" from repository and I am not able to install your package.
Could you suggest any way to debug or track this error down? Or manual install steps?

**Comment by kaneplusplus** [comment]
You could either download or clone the repository and use `R CMD INSTALL`.

Please note this does not sound like a `bittrex` specific issue. Presumably, this is a problem for any package you try to install with `devtools`.

**Comment by j4rd44** [comment]
Ok, I downloaded zip file, unzipped, compressed as tar.gz and only then the installation (R CMD INSTALL) went smoothly. Thank you for your support and also for this very useful tool.
