### ISSUE TITLE
adding codemeta.json metadata

### ISSUE THREAD

**Issue by chrisfan24** [ropensci/bittrex#7]
:wave: @kaneplusplus

messaged you earlier on ropensci slack but i haven't gotten a response yet, so i'm just restating here: I’m using codemetar to create JSON-LD metadata for rOpenSci packages. I’d like some info about bittrex when you have the time, since you’re the author / maintainer. In particular, I need your ORCID identifier as well as some keywords for the package that would help for search.

thanks michael! 😄

**Comment by kaneplusplus** [comment]
Hi @chrisfan24. Sorry, I don't check slack as much as I should. 

ORCID ID: 0000-0003-1899-6662.
Keywords: cryptocurrency, cryptocurrency exchange, finance
